### ISSUE TITLE
--sumary-in option bug

### ISSUE THREAD

**Issue by RxLoutre** [wdecoster/nanolyse#10]
Hi again Wouter ^^

Well, sorry but I had a tiny issue with the latest option to filter the sequencing_summary.

I gave a in and out option, he started to create the filtered seq_sum, but only wrote a line.
The error output says : 

```
NanoLyse: removed 180821 reads.
180821 lambda reads to remove from the summary
Traceback (most recent call last):
  File "/tools/python/3.6.3/bin/NanoLyse", line 8, in <module>
    sys.exit(main())
  File "/tools/python/3.6.3/lib/python3.6/site-packages/nanolyse/NanoLyse.py", line 51, in main
    filter_summary(args.summary_in, args.summary_out, tmp)
  File "/tools/python/3.6.3/lib/python3.6/site-packages/nanolyse/NanoLyse.py", line 147, in filter_summary
    index = header.split(b'\t').index(b'read_id')
ValueError: b'read_id' is not in list
```

Any ideas of something I might have done wrong ? The command : 
`
sbatch -p wflowq -J NanoLyseNew --mem=16G -t 04-00 --wrap "gunzip -c ${MAIS_RUN2}/20200819_1206_A1P1a-PlaGe-Mais-F2_M15-S05-L40_2-E1-H1_PAE96579_6f2a5308_PCT0078.fastq.gz | NanoLyse -r $REFERENCE --summary_in ${MAIS_RUN2}/20200819_1206_A1P1a-PlaGe-Mais-F2_M15-S05-L40_2-E1-H1_PAE96579_6f2a5308_PCT0078.sequencing_summary.txt --summary_out ${MAIS_RUN2}/20200819_1206_A1P1a-PlaGe-Mais-F2_M15-S05-L40_2-E1-H1_PAE96579_6f2a5308_PCT0078.sequencing_summary_filtered2.txt | gzip > ${MAIS_RUN2}/20200819_1206_A1P1a-PlaGe-Mais-F2_M15-S05-L40_2-E1-H1_PAE96579_6f2a5308_PCT0078_filteredDNAcs2.fastq.gz"`

**Comment by wdecoster** [comment]
Can you show me the header of the summary file?

**Comment by RxLoutre** [comment]
The header in the original file :

filename_fastq  filename_fast5  read_id run_id  channel mux     start_time      duration        num_events      passes_filtering        template_start  num_events_template     template_duration       sequence_length_template        mean_qscore_template      strand_score_template   median_template mad_template    pore_type       experiment_id   sample_id       end_reason

How he tried to write the first line in the filtered file : 

PAE96579_pass_9e59aa74_572.fastq        PAE96579_pass_9e59aa74_572.fast5        00000797-dc02-4887-a5a7-4448a357d25b    9e59aa7409646678d1e4abdabae0dd5361b7ba46        1835    3       34483.802250    51.524750       41219   TRUE    34484.059750      41013   51.267250       18969   9.898505        0.000000        72.738014       9.503459        not_set A1P1a-PlaGe-Mais        F2_M15-S05-L40  signal_positive

**Comment by wdecoster** [comment]
As @RxLoutre figured out on slack: there was something wrong with the input file :)
