### ISSUE TITLE
threads option?

### ISSUE THREAD

**Issue by Kirk3gaard** [wdecoster/nanolyse#14]
Hi

Does it have a threads option to benefit of minimap running with multiple threads?

Best regards
Rasmus

**Comment by wdecoster** [comment]
Hi Rasmus,

No, and I don't think it would help much. NanoLyse uses the mappy python API to minimap2, which only has multithreading when loading the index. Aligning reads is done one by one (streaming, without keeping everything in memory or using temporary files), for which threading cannot be used with mappy. This would probably only add overhead without making things faster.

If you have multiple fastq files you could of course run those in parallel.

Wouter

**Comment by Kirk3gaard** [comment]
Hi Wouter

Okay. Thanks a lot for the reply.

Best regards
Rasmus
