### ISSUE TITLE
Incorrect python version requirement in setup.py

### ISSUE THREAD

**Issue by ssantichaivekin** [wdecoster/nanolyse#15]
Hi team, I noticed that the setup.py says that this code requires any python 3 version. However, it uses f-string which requires python 3.6+. Do you mind either updating the python_requires in setup.py or remove the usages of f-string? Thanks so much. Really appreciate your work.

**Comment by wdecoster** [comment]
Thanks for the suggestion, I have updated the minimal version. Python 3.5 is EOL, so updating would be a good idea.
