### ISSUE TITLE
no option to designate log file path

### ISSUE THREAD

**Issue by nick-youngblut** [wdecoster/nanolyse#4]
It appears that there's no option to designate the path and file name for the log files generated by `nanolyse` and `nanofilt`. This can generate some problems when running multiple jobs with either of these commands, since each instance of `nanolyse` or `nanofilt` will try to write to the same file. This lack of path-designation for the log files can be especially problematic when using `nanolyse` or `nanofilt` in a `snakemake` pipeline.

**Comment by wdecoster** [comment]
Hi nick-youngblut,

That should be easy to add, thanks for the suggestion. I'll take care of it in the next few days. 

Cheers 
Wouter

**Comment by wdecoster** [comment]
I've added a `--logfile` argument to NanoFilt v2.2.0 and NanoLyse v1.1.0, which are available on PyPI/pip now.

Cheers,
Wouter
