### ISSUE TITLE
Please use release tags

### ISSUE THREAD

**Issue by tillea** [wdecoster/nanolyse#6]
Hi,
in the Debian Med COVID-19 sprint nanolyse was mentioned as a packaging target for official Debian.  It would help if you consider tagging your releases to enable us picking your right version right from github (in addition to the [PyPI download](https://pypi.org/project/NanoLyse/1.1.0/) since in some cases this is more convenient.
Kind regards, Andreas.

**Comment by wdecoster** [comment]
Right, I've made a release. Thanks!

**Comment by tillea** [comment]
On Mon, May 11, 2020 at 12:16:56PM -0700, Wouter De Coster wrote:
> Right, I've made a release. Thanks!
Thanks a lot for the fast and helpful response.  Andreas.

**Comment by tillea** [comment]
On Mon, May 11, 2020 at 12:16:56PM -0700, Wouter De Coster wrote:
> Right, I've made a release. Thanks!
Thanks for this.  Unfortunately github has only version 1.0 while PyPI has 1.1.0.
It would be great if you could bring both in sync.
Thanks a lot, Andreas.

**Comment by wdecoster** [comment]
I have no idea how that happened. I'll fix it.

**Comment by wdecoster** [comment]
Both are now at v1.1.1

**Comment by tillea** [comment]
On Thu, May 14, 2020 at 03:11:18AM -0700, Wouter De Coster wrote:
> Both are now at v1.1.1
Thanks a lot.  I think I have finished the packaging but the minimap2
package needs to build python3-mappy first.  We are working on this and
I'll come back in case of any remaining issues.
Kind regards, Andreas.
