### ISSUE TITLE
Not working with pip3??

### ISSUE THREAD

**Issue by fibrahim1** [wdecoster/nanolyse#7]
NanoLyse commands don't seem to run with pip3. Not even NanoLyse -h, NanoLyse --help or NanoLyse -v gives me feedback...

**Comment by fibrahim1** [comment]
(note: I installed using "pip3 install NanoLyse" instead of "pip install NanoLyse" like mentioned in the code description

**Comment by wdecoster** [comment]
> I installed using "pip3 install NanoLyse" 

Did the installation return any errors?

> Not even NanoLyse -h, NanoLyse --help or NanoLyse -v gives me feedback...

Just nothing happens or do you get an error?

**Comment by fibrahim1** [comment]
I get an error that says NanoLyse: command not found

**Comment by wdecoster** [comment]
Please repeat the installation and show me the output of pip(3).

**Comment by fibrahim1** [comment]
![Screenshot from 2020-06-01 19-09-27](https://user-images.githubusercontent.com/56319912/83701113-47858480-a5ce-11ea-94e0-af1d781003b1.png)

**Comment by wdecoster** [comment]
So installation was succesful, but the directory to which pip3 installs is not in your $PATH. I don't think this is a problem with NanoLyse, but rather with your setup. 

Please try `find / -name NanoLyse`

**Comment by fibrahim1** [comment]
Here is what I get when I try the command you mentioned:
![Screenshot from 2020-06-06 12-45-12](https://user-images.githubusercontent.com/56319912/83950906-a710a980-a7f3-11ea-8975-8845a45aa26c.png)

**Comment by wdecoster** [comment]
If we ignore all lines with "permission denied" you'll see that NanoLyse was installed in `/home/fujr/.local/bin/`. Please see if that directory is in $PATH and if not, add it. After restarting your terminal NanoLyse should then just work. See also [What is $PATH](https://askubuntu.com/questions/551990/what-does-path-mean).

Note that is basic Linux and not related specifically to NanoLyse. You would probably benefit from following some tutorials about the introduction to the command line.
