### ISSUE TITLE
More Examples on How to Use?

### ISSUE THREAD

**Issue by fibrahim1** [wdecoster/nanolyse#8]
Hello,

I was hoping to see other examples on how to use NanoLyse if someone were a bioinformatics beginner. Examples without zipped files?

Thank you!

**Comment by wdecoster** [comment]
Sure, I could add these, but why would your files not be zipped? As far as I know, there is no real eason not to keep fastq files gzipped all the time.

**Comment by fibrahim1** [comment]
That is true-- I was using a single fastq file to test out the command before I ran my actual data through the command

**Comment by wdecoster** [comment]
If not compressed you can just use cat to stream the fastq to NanoLyse.

**Comment by fibrahim1** [comment]
I will try that!

**Comment by wdecoster** [comment]
Please let me know if you have any further questions or issues
