### ISSUE TITLE
Features ideas

### ISSUE THREAD

**Issue by RxLoutre** [wdecoster/nanolyse#9]
Very cool tool !

Would be even cooler for us if it was also :
-Reporting how many reads he discarded in its log
-Filter the reads out of a given sequencing summary too (the sequencing_summary being optionnal)

Would that be too annoying to do ? If it is not made already ? (Sadly our cluster facility has installed only previous version and cannot successfully install the new one).

**Comment by wdecoster** [comment]
Hi Roxane,

Good ideas! I'll probably not have time for these this week though.

> Reporting how many reads he discarded in its log

Should be easy :)

> Filter the reads out of a given sequencing summary too (the sequencing_summary being optionnal)

Hmm that would be possible, but I probably would be in favor to put that functionality in a separate script. I'll give it some more thought.

> Sadly our cluster facility has installed only previous version and cannot successfully install the new one

What's the installation problem?

Cheers,
Wouter

**Comment by RxLoutre** [comment]
Nice :)

I am in no rush, I'll try a way to do it manually for the test. But I think I'm going to ask to add NaoLyse in our routine analysis pipeline, if they decide to add DNAcs in all our nanopore runs.

For the sequencing_summary, it would have been nice because many tools performs graph and stats based ont he sequencing summary, and I wanted to check if the tiny peak of reads around 4.5 KB was gone after NanoLyse.. Not that I doubt your tool ofc but has to be checked :p 

The person who tried to install it didn't told me what was wrong. I am going to ask him more details and I'll forward them.

**Comment by wdecoster** [comment]
> Reporting how many reads he discarded in its log

Is done now in v1.1.4 ;-)

> The person who tried to install it didn't told me what was wrong. I am going to ask him more details and I'll forward them.

Thanks! If the previous version worked, then the current version should too. Nothing major changed the last couple of ehm, years.

**Comment by RxLoutre** [comment]
Oh wow that's fast :o
With the sequencing summary option too ?
Thanks a lot anyway :D

**Comment by wdecoster** [comment]
> Oh wow that's fast :o

That's the advantage of attending meetings remotely :)

> With the sequencing summary option too ?

Nope, that part not.

**Comment by RxLoutre** [comment]
Ah, a shame ^^ Can it then print the ID of the reads he removes ? 🙏

**Comment by wdecoster** [comment]
Not today, I've got to think more about the implementation first.

**Comment by wdecoster** [comment]
As we discussed on Slack you know have a bash way to get the new summary file - does that one suffice or would you still like a (Python) script? I don't think I can improve on the speed of your approach using join :)

**Comment by RxLoutre** [comment]
I think I would still really like it if it was directly included in Nanolyse. I don't know if it is feasible though.
Indeed, the join work pretty nice but it require first to get a list from all reads from the cleaned fastq.gz tha Nanolyse produce, for that I have been using seqkit seq -n, but it took me around a day because I had large fastq files.

But I get that Nanolyse is more writing a read that doesn't map than discarding a read that map... So it wouldn't really be easy to implement such a function in withiin the tool :/ What do you think ?

**Comment by wdecoster** [comment]
I've thought of a reasonable approach, and I will probably implement it tomorrow.

**Comment by RxLoutre** [comment]
Oho ! Hype :)

**Comment by wdecoster** [comment]
NanoLyse 1.2.0 (available on PyPI) has a --summary_in and --summary_out option to optionally filter a summary - feedback welcome :)

**Comment by RxLoutre** [comment]
This is great thanks ! :) I will test it as soon as it will be updated on our cluster. I'll give you insight if they have error to install it.
